sudo: false

language: python

# Python versions to build
python:
  - "2.7"

# command(s) to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# build command(s)
script: coverage run --source=autosubliminal setup.py test

# after success command(s)
after_success: coveralls
